spring.application.name=Gateway-Service

server.port=8888
eureka.instance.hostname=localhost
eureka.client.service-url.default-zone=http://localhost:8761/eureka
# http://localhost:8888/notification-service/notification
# http://localhost:8888/compras-ventas/permiso
spring.cloud.gateway.routes[0].id=compras-ventas
spring.cloud.gateway.routes[0].uri=http://localhost:8089
spring.cloud.gateway.routes[0].predicates=Path=/compras-ventas/api/**
spring.cloud.gateway.routes[1].id=Notification-Service
spring.cloud.gateway.routes[1].uri=http://localhost:8090
spring.cloud.gateway.routes[1].predicates=Path=/Notification-Service/**